# A sample Gemfile
source "http://rubygems.org"

# gem "rails"
gem "activerecord", "3.0.5"
gem "activerecord-jdbc-adapter", "1.1.3"
gem "arel", "2.2.1"
gem "color", "1.4.1"
gem "cucumber"
gem "i18n", "0.6.0"
gem "jruby-openssl", "0.7.4"
gem "rack", "1.3.2"
gem "rest-open-uri", "1.0.0"
gem "rspec", "2.6.0"
gem "ruby-debug"
gem "watir-webdriver"

